name: Deploy n8n to DigitalOcean Droplet

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy files to Droplet
      run: |
        rsync -avz -e "sshpass -p '${{ secrets.DROPLET_PASSWORD }}' ssh -o StrictHostKeyChecking=no" ./n8n/ vyrana@68.183.85.180:/home/vyrana/n8n.vyrana.com/

    - name: Deploy with Docker Compose
      run: |
        sshpass -p '${{ secrets.DROPLET_PASSWORD }}' ssh -o StrictHostKeyChecking=no vyrana@68.183.85.180 '
          cd /home/vyrana/n8n && \
          docker compose pull && \
          docker compose up -d --remove-orphans
        '

    - name: Post-deployment health check
      run: |
        sshpass -p '${{ secrets.DROPLET_PASSWORD }}' ssh -o StrictHostKeyChecking=no vyrana@68.183.85.180 'docker compose ps'

# ---
# Setup instructions:
# 1. Add the following repository secret in GitHub:
#    - DROPLET_PASSWORD:The SSH password for vyrana@68.183.85.180
# 2. This workflow will rsync your n8n folder and run docker compose up on the droplet.
# 3. For production, secure your droplet, use strong credentials, and set up monitoring/backups.
